name: Profile Summary Cards
on:
  push:
    paths:
      - .github/workflows/summary-cards.yml
      - README.md
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Bashmak-1
          BRANCH_NAME: main
          UTC_OFFSET: +0300
          AUTO_PUSH: true
          EXCLUDE: productive-time